order.api=http://localhost:8090
management.endpoints.web.exposure.include=*
server.port=8080

spring.kafka.bootstrap-servers=localhost:9092
kafka.topic=product-queries
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer